"""factor/v4/formulas/{} — V4 AST 语法"""

from typing import Dict

ALPHA101: Dict[str, str] = {
    "alpha001": "(cs_rank(ts_argmax(signed_power((ts_std(RETURNS, 20) if (-RETURNS) else CLOSE), 2), 5)) - 0.5)",
    "alpha002": "(-ts_corr(cs_rank((log(VOLUME) - ts_delay(log(VOLUME), 2))), cs_rank(((CLOSE - OPEN) / OPEN)), 6))",
    "alpha003": "(-ts_corr(cs_rank(OPEN), cs_rank(VOLUME), 10))",
    "alpha004": "(-ts_rank(cs_rank(LOW), 9))",
    "alpha005": "(cs_rank((OPEN - ts_mean(OPEN, 10))) * (-abs((CLOSE - ts_delay(CLOSE, 1)))))",
    "alpha006": "(-ts_corr(OPEN, VOLUME, 10))",
    "alpha007": "(((-ts_rank(abs((CLOSE - ts_delay(CLOSE, 7))), 60)) * sign((CLOSE - ts_delay(CLOSE, 7)))) if (VOLUME - ts_mean(VOLUME, 20)) else -1)",
    "alpha008": "(-cs_rank(((ts_sum(OPEN, 5) * ts_sum(RETURNS, 5)) - ts_delay((ts_sum(OPEN, 5) * ts_sum(RETURNS, 5)), 10))))",
    "alpha009": "((CLOSE - ts_delay(CLOSE, 1)) if ts_min((CLOSE - ts_delay(CLOSE, 1)), 5) else ((CLOSE - ts_delay(CLOSE, 1)) if (-ts_max((CLOSE - ts_delay(CLOSE, 1)), 5)) else (-(CLOSE - ts_delay(CLOSE, 1)))))",
    "alpha010": "cs_rank(((CLOSE - ts_delay(CLOSE, 1)) if ts_min((CLOSE - ts_delay(CLOSE, 1)), 4) else ((CLOSE - ts_delay(CLOSE, 1)) if (-ts_max((CLOSE - ts_delay(CLOSE, 1)), 4)) else (-(CLOSE - ts_delay(CLOSE, 1))))))",
    "alpha011": "((cs_rank(ts_max((VWAP - CLOSE), 3)) + cs_rank(ts_min((VWAP - CLOSE), 3))) * cs_rank((VOLUME - ts_delay(VOLUME, 3))))",
    "alpha012": "(sign((VOLUME - ts_delay(VOLUME, 1))) * (-(CLOSE - ts_delay(CLOSE, 1))))",
    "alpha013": "(-cs_rank(ts_cov(cs_rank(CLOSE), cs_rank(VOLUME), 5)))",
    "alpha014": "((-cs_rank((RETURNS - ts_delay(RETURNS, 3)))) * ts_corr(OPEN, VOLUME, 10))",
    "alpha015": "(-ts_sum(cs_rank(ts_corr(cs_rank(HIGH), cs_rank(VOLUME), 3)), 3))",
    "alpha016": "(-cs_rank(ts_cov(cs_rank(HIGH), cs_rank(VOLUME), 5)))",
    "alpha017": "(((-cs_rank(ts_rank(CLOSE, 10))) * cs_rank(((CLOSE - ts_delay(CLOSE, 1)) - ts_delay((CLOSE - ts_delay(CLOSE, 1)), 1)))) * cs_rank(ts_rank((VOLUME / ts_mean(VOLUME, 20)), 5)))",
    "alpha018": "(-cs_rank(((ts_std(abs((CLOSE - OPEN)), 5) + (CLOSE - OPEN)) + ts_corr(CLOSE, OPEN, 10))))",
    "alpha019": "((-sign(((CLOSE - ts_delay(CLOSE, 7)) + (CLOSE - ts_delay(CLOSE, 7))))) * (1 + cs_rank((1 + ts_sum(RETURNS, 250)))))",
    "alpha020": "(((-cs_rank((OPEN - ts_delay(HIGH, 1)))) * cs_rank((OPEN - ts_delay(CLOSE, 1)))) * cs_rank((OPEN - ts_delay(LOW, 1))))",
    "alpha021": "(-1 if (((ts_sum(CLOSE, 8) / 8) + ts_std(CLOSE, 8)) - (ts_sum(CLOSE, 2) / 2)) else 1)",
    "alpha022": "((-(ts_corr(HIGH, VOLUME, 5) - ts_delay(ts_corr(HIGH, VOLUME, 5), 5))) * cs_rank(ts_std(CLOSE, 20)))",
    "alpha023": "((-(HIGH - ts_delay(HIGH, 2))) if ((ts_sum(HIGH, 20) / 20) - HIGH) else 0)",
    "alpha024": "(((-CLOSE) / ((ts_sum(CLOSE, 100) / 100) - CLOSE)) if (0.05 - (((ts_sum(CLOSE, 100) / 100) - ts_delay((ts_sum(CLOSE, 100) / 100), 100)) / ts_delay(CLOSE, 100))) else (-log(CLOSE)))",
    "alpha025": "cs_rank(((((-RETURNS) * ts_mean(VOLUME, 20)) * VWAP) * (HIGH - CLOSE)))",
    "alpha026": "(-ts_max(ts_corr(ts_rank(VOLUME, 5), ts_rank(HIGH, 5), 5), 3))",
    "alpha027": "(1 if (cs_rank(ts_corr(cs_rank(VOLUME), cs_rank(VWAP), 6)) - 0.5) else -1)",
    "alpha028": "((ts_corr(ts_mean(VOLUME, 20), LOW, 5) + ((HIGH + LOW) / 2)) - CLOSE)",
    "alpha029": "(ts_min(cs_rank(log(ts_sum(cs_rank((-cs_rank((CLOSE - ts_delay(CLOSE, 1))))), 15))), 5) + ts_rank(ts_delay((-RETURNS), 6), 5))",
    "alpha030": "(((1 - cs_rank(((sign((CLOSE - ts_delay(CLOSE, 1))) + sign((ts_delay(CLOSE, 1) - ts_delay(CLOSE, 2)))) + sign((ts_delay(CLOSE, 2) - ts_delay(CLOSE, 3)))))) * ts_sum(VOLUME, 5)) / ts_sum(VOLUME, 20))",
    "alpha031": "((cs_rank(ts_decay_linear((-cs_rank((CLOSE - ts_delay(CLOSE, 10)))), 10)) + cs_rank((-(CLOSE - ts_delay(CLOSE, 3))))) + sign(ts_corr(ts_mean(VOLUME, 20), LOW, 12)))",
    "alpha032": "(((ts_sum(CLOSE, 7) / 7) - CLOSE) + (20 * ts_corr(VWAP, ts_delay(CLOSE, 5), 230)))",
    "alpha033": "cs_rank((-(1 - (OPEN / CLOSE))))",
    "alpha034": "cs_rank(((1 - cs_rank((ts_std(RETURNS, 2) / ts_std(RETURNS, 5)))) + (1 - cs_rank((CLOSE - ts_delay(CLOSE, 1))))))",
    "alpha035": "((ts_rank(VOLUME, 32) * (1 - ts_rank(((CLOSE + HIGH) - LOW), 16))) * (1 - ts_rank(RETURNS, 32)))",
    "alpha036": "(((((2.21 * cs_rank(ts_corr((CLOSE - OPEN), ts_delay(VOLUME, 1), 15))) + (0.7 * cs_rank((OPEN - CLOSE)))) + (0.73 * cs_rank(ts_rank(ts_delay((-RETURNS), 6), 5)))) + cs_rank(abs(ts_corr(VWAP, ts_mean(VOLUME, 20), 6)))) + (0.6 * cs_rank((((ts_sum(CLOSE, 200) / 200) - OPEN) * (CLOSE - OPEN)))))",
    "alpha037": "(cs_rank(ts_corr(ts_delay((OPEN - CLOSE), 1), CLOSE, 200)) + cs_rank((OPEN - CLOSE)))",
    "alpha038": "((-cs_rank(ts_rank(CLOSE, 10))) * cs_rank((CLOSE / OPEN)))",
    "alpha039": "((-cs_rank(((CLOSE - ts_delay(CLOSE, 7)) * (1 - cs_rank(ts_decay_linear((VOLUME / ts_mean(VOLUME, 20)), 9)))))) * (1 + cs_rank(ts_sum(RETURNS, 250))))",
    "alpha040": "((-cs_rank(ts_std(HIGH, 10))) * ts_corr(HIGH, VOLUME, 10))",
    "alpha041": "(sqrt((HIGH * LOW)) - VWAP)",
    "alpha042": "(cs_rank((VWAP - CLOSE)) / cs_rank((VWAP + CLOSE)))",
    "alpha043": "(ts_rank(ts_mean(VOLUME, 20), 20) * ts_rank((-(CLOSE - ts_delay(CLOSE, 7))), 8))",
    "alpha044": "(-ts_corr(HIGH, cs_rank(VOLUME), 5))",
    "alpha045": "((-cs_rank((((CLOSE * 0.6) + (OPEN * 0.4)) - ts_delay(((CLOSE * 0.6) + (OPEN * 0.4)), 1)))) * cs_rank(ts_corr(VWAP, ts_mean(VOLUME, 20), 15)))",
    "alpha046": "((((ts_mean(CLOSE, 3) + ts_mean(CLOSE, 6)) + ts_mean(CLOSE, 12)) + ts_mean(CLOSE, 24)) / (4 * CLOSE))",
    "alpha047": "ts_delay(ts_mean((((ts_max(HIGH, 6) - CLOSE) / (ts_max(HIGH, 6) - ts_min(LOW, 6))) * 100), 9), 1)",
    "alpha048": "((-ts_corr(cs_rank(HIGH), cs_rank(VOLUME), 5)) * ts_rank(VOLUME, 5))",
    "alpha049": "(((-CLOSE) / ts_delay(CLOSE, 20)) if ((((ts_delay(CLOSE, 20) - ts_delay(CLOSE, 10)) / 10) - ((ts_delay(CLOSE, 10) - CLOSE) / 10)) + 0.05) else 1)",
    "alpha050": "(-ts_max(cs_rank(ts_corr(cs_rank(VOLUME), cs_rank(VWAP), 5)), 5))",
    "alpha051": "(-1 if ((((ts_delay(CLOSE, 20) - ts_delay(CLOSE, 10)) / 10) - ((ts_delay(CLOSE, 10) - CLOSE) / 10)) + 0.05) else 1)",
    "alpha052": "((((-ts_min(LOW, 5)) + ts_delay(ts_min(LOW, 5), 5)) * cs_rank(((ts_sum(RETURNS, 240) - ts_sum(RETURNS, 20)) / 220))) * ts_rank(VOLUME, 5))",
    "alpha053": "(-((((CLOSE - LOW) - (HIGH - CLOSE)) / (CLOSE - LOW)) - ts_delay((((CLOSE - LOW) - (HIGH - CLOSE)) / (CLOSE - LOW)), 9)))",
    "alpha054": "((-((LOW - CLOSE) * signed_power(OPEN, 5))) / ((LOW - HIGH) * signed_power(CLOSE, 5)))",
    "alpha055": "(-ts_corr(cs_rank(((CLOSE - ts_min(LOW, 12)) / (ts_max(HIGH, 12) - ts_min(LOW, 12)))), cs_rank(VOLUME), 6))",
    "alpha056": "(-(cs_rank((ts_sum(RETURNS, 10) / ts_sum(ts_sum(RETURNS, 2), 3))) * cs_rank(RETURNS)))",
    "alpha057": "(-((CLOSE - VWAP) / ts_decay_linear(cs_rank(ts_argmax(CLOSE, 30)), 2)))",
    "alpha058": "(-ts_rank(ts_decay_linear(ts_corr(VWAP, VOLUME, 4), 8), 6))",
    "alpha059": "(-ts_rank(ts_decay_linear(ts_corr(VWAP, VOLUME, 5), 6), 4))",
    "alpha060": "(-((2 * cs_rank(((((CLOSE - LOW) - (HIGH - CLOSE)) / (HIGH - LOW)) * VOLUME))) - cs_rank(ts_argmax(CLOSE, 10))))",
    "alpha061": "(cs_rank((VWAP - ts_min(VWAP, 16))) - cs_rank(ts_corr(VWAP, ts_mean(VOLUME, 180), 18)))",
    "alpha062": "(cs_rank(ts_corr(VWAP, ts_sum(ts_mean(VOLUME, 20), 22), 10)) - cs_rank(((cs_rank(OPEN) + cs_rank(OPEN)) - (cs_rank(((HIGH + LOW) / 2)) + cs_rank(HIGH)))))",
    "alpha063": "(-(cs_rank(ts_decay_linear((CLOSE - ts_delay(CLOSE, 2)), 8)) - cs_rank(ts_decay_linear((ts_sum(VOLUME, 10) / ts_mean(VOLUME, 10)), 1))))",
    "alpha064": "(cs_rank(ts_corr(ts_sum(((OPEN * 0.178) + (LOW * 0.822)), 13), ts_sum(ts_mean(VOLUME, 120), 13), 17)) - cs_rank((((((HIGH + LOW) / 2) * 0.178) + (VWAP * 0.822)) - ts_delay(((((HIGH + LOW) / 2) * 0.178) + (VWAP * 0.822)), 4))))",
    "alpha065": "(cs_rank(ts_corr(((OPEN * 0.008) + (VWAP * 0.992)), ts_sum(ts_mean(VOLUME, 60), 9), 6)) - cs_rank((OPEN - ts_min(OPEN, 14))))",
    "alpha066": "(-(cs_rank(ts_decay_linear((VWAP - ts_delay(VWAP, 4)), 7)) + ts_rank(ts_decay_linear(((LOW - VWAP) / (OPEN - ((HIGH + LOW) / 2))), 11), 7)))",
    "alpha067": "ts_delay(ts_mean((((CLOSE - ts_delay(ts_mean(CLOSE, 10), 1)) / ts_delay(ts_mean(CLOSE, 10), 1)) * 100), 2), 1)",
    "alpha068": "ts_delay(ts_mean((((((HIGH + LOW) / 2) - ts_delay(ts_mean(((HIGH + LOW) / 2), 15), 2)) / (0.5 * ts_delay(ts_mean(abs((((HIGH + LOW) / 2) - ts_delay(ts_mean(((HIGH + LOW) / 2), 15), 2))), 15), 2))) * 100), 2), 1)",
    "alpha069": "(-signed_power(cs_rank(ts_max((VWAP - ts_delay(VWAP, 3)), 5)), ts_rank(ts_corr(((CLOSE * 0.491) + (VWAP * 0.509)), ts_mean(VOLUME, 20), 5), 9)))",
    "alpha070": "ts_delay(ts_mean((((CLOSE - ts_delay(ts_mean(CLOSE, 10), 2)) / ts_delay(ts_mean(CLOSE, 10), 2)) * 100), 2), 1)",
    "alpha071": "(-cs_rank(ts_decay_linear(ts_corr(ts_rank(CLOSE, 3), cs_rank(VOLUME), 5), 7)))",
    "alpha072": "ts_rank(ts_decay_linear(ts_corr(((HIGH + LOW) / 2), ts_mean(VOLUME, 40), 9), 4), 2)",
    "alpha073": "ts_rank(ts_decay_linear(ts_corr(((HIGH + LOW) / 2), ts_mean(VOLUME, 40), 5), 3), 2)",
    "alpha074": "(cs_rank(ts_corr(CLOSE, ts_sum(ts_mean(VOLUME, 30), 37), 15)) - cs_rank(ts_corr(cs_rank(((HIGH * 0.026) + (VWAP * 0.974))), cs_rank(VOLUME), 11)))",
    "alpha075": "(cs_rank(ts_corr(VWAP, VOLUME, 4)) - cs_rank(ts_corr(cs_rank(LOW), cs_rank(ts_mean(VOLUME, 50)), 12)))",
    "alpha076": "ts_rank(ts_decay_linear(ts_corr(VWAP, VOLUME, 17), 20), 3)",
    "alpha077": "ts_rank(ts_decay_linear(((((HIGH + LOW) / 2) + HIGH) - (VWAP + HIGH)), 9), 4)",
    "alpha078": "signed_power(cs_rank(ts_corr(ts_sum(((LOW * 0.352) + (VWAP * 0.648)), 20), ts_sum(ts_mean(VOLUME, 40), 20), 7)), cs_rank(ts_corr(cs_rank(VWAP), cs_rank(VOLUME), 6)))",
    "alpha079": "signed_power(cs_rank((((CLOSE * 0.607) + (OPEN * 0.393)) - ts_delay(((CLOSE * 0.607) + (OPEN * 0.393)), 4))), ts_rank(ts_corr(ts_rank(VWAP, 3), ts_rank(ts_mean(VOLUME, 81), 9), 12), 3))",
    "alpha080": "(-(cs_rank(sign((((OPEN * 0.868) + (HIGH * 0.132)) - ts_delay(((OPEN * 0.868) + (HIGH * 0.132)), 4)))) * ts_rank(ts_corr(HIGH, ts_mean(VOLUME, 10), 5), 6)))",
    "alpha081": "(-(cs_rank(log(cs_rank(signed_power(cs_rank(ts_corr(VWAP, ts_sum(ts_mean(VOLUME, 10), 50), 8)), 4)))) - cs_rank(ts_corr(cs_rank(VWAP), cs_rank(VOLUME), 5))))",
    "alpha082": "(-ts_min(cs_rank(ts_decay_linear((OPEN - ts_delay(OPEN, 1)), 15)), 5))",
    "alpha083": "((cs_rank(ts_delay(((HIGH - LOW) / (ts_sum(CLOSE, 5) / 5)), 2)) * cs_rank(cs_rank(VOLUME))) / (((HIGH - LOW) / (ts_sum(CLOSE, 5) / 5)) / (VWAP - CLOSE)))",
    "alpha084": "signed_power(ts_rank((VWAP - ts_max(VWAP, 15)), 21), (CLOSE - ts_delay(CLOSE, 5)))",
    "alpha085": "signed_power(cs_rank(ts_corr(((HIGH * 0.877) + (CLOSE * 0.123)), ts_mean(VOLUME, 30), 10)), cs_rank(ts_corr(ts_rank(((HIGH + LOW) / 2), 4), ts_rank(VOLUME, 10), 15)))",
    "alpha086": "(-(ts_rank(ts_corr(CLOSE, ts_sum(ts_mean(VOLUME, 20), 15), 6), 20) - cs_rank(((OPEN + CLOSE) - (VWAP + OPEN)))))",
    "alpha087": "ts_delay(ts_mean((((CLOSE - ts_delay(ts_mean(CLOSE, 10), 2)) / ts_delay(ts_mean(CLOSE, 10), 2)) * 100), 2), 2)",
    "alpha088": "cs_rank(ts_decay_linear(((cs_rank(OPEN) + cs_rank(LOW)) - (cs_rank(HIGH) + cs_rank(CLOSE))), 8))",
    "alpha089": "(ts_rank(ts_decay_linear(ts_corr(LOW, ts_mean(VOLUME, 10), 7), 6), 4) - ts_rank(ts_decay_linear((VWAP - ts_delay(VWAP, 3)), 10), 15))",
    "alpha090": "(-(cs_rank((CLOSE - ts_max(CLOSE, 5))) * ts_rank(ts_corr(VWAP, ts_mean(VOLUME, 40), 9), 7)))",
    "alpha091": "ts_delay(ts_mean(ts_delay(ts_mean((((CLOSE - ts_delay(ts_mean(CLOSE, 8), 1)) / ts_delay(ts_mean(CLOSE, 8), 1)) * 100), 3), 1), 3), 1)",
    "alpha092": "ts_rank(ts_decay_linear(ts_corr((((HIGH + LOW) / 2) + CLOSE), ts_mean(VOLUME, 10), 12), 7), 16)",
    "alpha093": "ts_rank(ts_decay_linear(ts_corr(VWAP, ts_mean(VOLUME, 81), 17), 6), 6)",
    "alpha094": "(-(cs_rank((VWAP - ts_min(VWAP, 12))) * ts_rank(ts_corr(ts_rank(VWAP, 20), ts_rank(ts_mean(VOLUME, 60), 4), 18), 3)))",
    "alpha095": "(cs_rank((OPEN - ts_min(OPEN, 12))) - ts_rank(signed_power(cs_rank(ts_corr(ts_sum(((HIGH + LOW) / 2), 19), ts_sum(ts_mean(VOLUME, 40), 19), 13)), 5), 12))",
    "alpha096": "(-ts_rank(ts_decay_linear(ts_corr(cs_rank(VWAP), cs_rank(VOLUME), 6), 7), 5))",
    "alpha097": "(-(cs_rank(ts_decay_linear((((LOW * 0.721) + (VWAP * 0.279)) - ts_delay(((LOW * 0.721) + (VWAP * 0.279)), 3)), 20)) - ts_rank(ts_decay_linear(ts_rank(ts_corr(ts_rank(LOW, 8), ts_rank(ts_mean(VOLUME, 60), 17), 5), 19), 15), 7)))",
    "alpha098": "(cs_rank(ts_decay_linear(ts_corr(VWAP, ts_sum(ts_mean(VOLUME, 5), 26), 5), 7)) - 5.236)",
    "alpha099": "(-(cs_rank(ts_corr(ts_sum(((HIGH + LOW) / 2), 20), ts_sum(ts_mean(VOLUME, 60), 20), 9)) - cs_rank(ts_corr(LOW, VOLUME, 6))))",
    "alpha100": "(-((1.5 * cs_rank(((((CLOSE - LOW) - (HIGH - CLOSE)) / (HIGH - LOW)) * VOLUME))) - (ts_corr(CLOSE, cs_rank(ts_mean(VOLUME, 20)), 5) - cs_rank(ts_argmin(CLOSE, 30)))))",
    "alpha101": "((CLOSE - OPEN) / ((HIGH - LOW) + 0.001))",
}
