"""factor/v4/formulas/{} — V4 AST 语法"""

from typing import Dict

ALPHA191: Dict[str, str] = {
    "gtja_001": "cs_rank((CLOSE - ts_delay(CLOSE, 5)))",
    "gtja_002": "((CLOSE - ts_delay(CLOSE, 20)) * (VOLUME - ts_delay(VOLUME, 5)))",
    "gtja_003": "cs_rank(((CLOSE - ts_delay(CLOSE, 1)) * VOLUME))",
    "gtja_004": "((CLOSE - ts_delay(CLOSE, 5)) * (VOLUME / ts_mean(VOLUME, 20)))",
    "gtja_005": "cs_rank(((CLOSE - ts_delay(CLOSE, 1)) * (VOLUME / ts_mean(VOLUME, 20))))",
    "gtja_006": "(ts_rank((CLOSE - ts_delay(CLOSE, 1)), 10) * (-ts_std((CLOSE - ts_delay(CLOSE, 1)), 10)))",
    "gtja_007": "ts_rank((CLOSE - ts_delay(CLOSE, 1)), 20)",
    "gtja_008": "(ts_rank((CLOSE - ts_delay(CLOSE, 1)), 5) + ts_rank(VOLUME, 5))",
    "gtja_009": "ts_decay_linear((CLOSE - ts_delay(CLOSE, 1)), 4)",
    "gtja_010": "((CLOSE - ts_delay(CLOSE, 5)) * (-ts_std((CLOSE - ts_delay(CLOSE, 1)), 20)))",
    "gtja_011": "((VOLUME - ts_delay(VOLUME, 5)) * (CLOSE - ts_delay(CLOSE, 5)))",
    "gtja_012": "ts_decay_linear((CLOSE - ts_delay(CLOSE, 1)), 20)",
    "gtja_013": "((((HIGH + LOW) / 2) - ts_delay(((HIGH + LOW) / 2), 20)) - (CLOSE - ts_delay(CLOSE, 20)))",
    "gtja_014": "(-cs_rank(ts_argmax(CLOSE, 30)))",
    "gtja_015": "cs_rank(ts_argmin(CLOSE, 30))",
    "gtja_016": "(ts_max(CLOSE, 20) - ts_min(CLOSE, 20))",
    "gtja_017": "((CLOSE - ts_min(CLOSE, 20)) / (ts_max(CLOSE, 20) - ts_min(CLOSE, 20)))",
    "gtja_018": "((CLOSE - ts_delay(CLOSE, 10)) * ((CLOSE - ts_delay(CLOSE, 1)) - ts_delay((CLOSE - ts_delay(CLOSE, 1)), 1)))",
    "gtja_019": "(ts_mean((CLOSE - ts_delay(CLOSE, 1)), 20) - ts_std((CLOSE - ts_delay(CLOSE, 1)), 20))",
    "gtja_020": "cs_rank((CLOSE - VWAP))",
    "gtja_021": "cs_rank((CLOSE - ts_delay(ts_mean(CLOSE, 20), 1)))",
    "gtja_022": "((CLOSE - ts_delay(ts_mean(CLOSE, 20), 1)) / ts_delay(ts_mean(CLOSE, 20), 1))",
    "gtja_023": "(CLOSE / ts_delay(ts_mean(CLOSE, 20), 1))",
    "gtja_024": "((CLOSE - ts_delay(CLOSE, 20)) / ts_std((CLOSE - ts_delay(CLOSE, 1)), 20))",
    "gtja_025": "((CLOSE - ts_delay(CLOSE, 5)) * ts_corr(CLOSE, VOLUME, 20))",
    "gtja_026": "(CLOSE - ts_mean(CLOSE, 20))",
    "gtja_027": "(CLOSE - ts_max(CLOSE, 5))",
    "gtja_028": "((ts_max(CLOSE, 20) - ts_min(CLOSE, 20)) / ts_mean(CLOSE, 20))",
    "gtja_029": "((CLOSE - ts_delay(CLOSE, 1)) * ts_rank(VOLUME, 20))",
    "gtja_030": "(ts_rank(CLOSE, 10) - ts_rank(VOLUME, 10))",
    "gtja_031": "(-ts_rank((CLOSE - ts_delay(CLOSE, 1)), 5))",
    "gtja_032": "(-((CLOSE - ts_delay(CLOSE, 20)) * ts_rank(VOLUME, 5)))",
    "gtja_033": "(-((CLOSE - VWAP) * ts_rank(VOLUME, 5)))",
    "gtja_034": "(-ts_decay_linear((CLOSE - ts_delay(CLOSE, 1)), 10))",
    "gtja_035": "(-ts_zscore((CLOSE - ts_delay(CLOSE, 1)), 20))",
    "gtja_036": "(-ts_rank((CLOSE - ts_delay(CLOSE, 1)), 30))",
    "gtja_037": "(-ts_rank(CLOSE, 45))",
    "gtja_038": "(-ts_rank(CLOSE, 60))",
    "gtja_039": "(-((CLOSE - ts_delay(CLOSE, 5)) * (VOLUME / ts_mean(VOLUME, 20))))",
    "gtja_040": "(-cs_rank(((CLOSE - ts_delay(CLOSE, 1)) * (VOLUME / ts_delay(VOLUME, 1)))))",
    "gtja_041": "((CLOSE - LOW) / ((HIGH - LOW) + 0.001))",
    "gtja_042": "(ts_mean(((CLOSE - ts_delay(CLOSE, 1)) if (CLOSE - ts_delay(CLOSE, 1)) else 0.0), 14) / (ts_mean(abs((CLOSE - ts_delay(CLOSE, 1))), 14) + 0.001))",
    "gtja_043": "(-(HIGH - ts_delay(HIGH, 10)))",
    "gtja_044": "(-cs_rank(((CLOSE - OPEN) * VOLUME)))",
    "gtja_045": "(-ts_corr(ts_rank(CLOSE, 5), ts_rank(VOLUME, 5), 10))",
    "gtja_046": "(-ts_cov(CLOSE, VOLUME, 10))",
    "gtja_047": "(-ts_rank((((CLOSE - OPEN) / (OPEN + 0.001)) * VOLUME), 5))",
    "gtja_048": "cs_rank(ts_argmax(CLOSE, 60))",
    "gtja_049": "(-cs_rank(ts_argmin(CLOSE, 60)))",
    "gtja_050": "(-((CLOSE - ts_min(CLOSE, 20)) / ((ts_max(CLOSE, 20) - ts_min(CLOSE, 20)) + 0.001)))",
    "gtja_051": "(-ts_rank((CLOSE - ts_delay(CLOSE, 1)), 20))",
    "gtja_052": "(cs_rank((-(CLOSE - ts_delay(CLOSE, 1)))) * ts_rank(VOLUME, 20))",
    "gtja_053": "((OPEN - ts_delay(CLOSE, 1)) / (ts_delay(CLOSE, 1) + 0.001))",
    "gtja_054": "ts_corr((-(CLOSE - ts_delay(CLOSE, 1))), ts_rank(VOLUME, 5), 20)",
    "gtja_055": "(-ts_rank((CLOSE - ts_delay(CLOSE, 60)), 10))",
    "gtja_056": "(-(CLOSE - ts_max(CLOSE, 20)))",
    "gtja_057": "(-ts_rank((CLOSE / ts_delay(ts_mean(CLOSE, 20), 1)), 10))",
    "gtja_058": "(-((CLOSE - ts_delay(CLOSE, 1)) if (ts_delay(CLOSE, 1) - CLOSE) else 0.0))",
    "gtja_059": "(-(((CLOSE - ts_delay(CLOSE, 5)) / (ts_std((CLOSE - ts_delay(CLOSE, 1)), 20) + 0.001)) * ts_rank(VOLUME, 20)))",
    "gtja_060": "(cs_rank((-(CLOSE - ts_delay(CLOSE, 10)))) * ts_corr(CLOSE, VOLUME, 10))",
    "gtja_061": "(-ts_std((CLOSE - ts_delay(CLOSE, 1)), 20))",
    "gtja_062": "(-ts_std((CLOSE - ts_delay(CLOSE, 1)), 10))",
    "gtja_063": "(-ts_std((CLOSE - ts_delay(CLOSE, 1)), 60))",
    "gtja_064": "(-ts_zscore((CLOSE - ts_delay(CLOSE, 1)), 20))",
    "gtja_065": "(-ts_zscore((CLOSE - ts_delay(CLOSE, 1)), 10))",
    "gtja_066": "(-ts_zscore((CLOSE - ts_delay(CLOSE, 1)), 60))",
    "gtja_067": "(-ts_std((0.0 if (CLOSE - ts_delay(CLOSE, 1)) else (CLOSE - ts_delay(CLOSE, 1))), 20))",
    "gtja_068": "(-((HIGH - LOW) / (CLOSE + 0.001)))",
    "gtja_069": "(-(ts_mean((HIGH - LOW), 20) / CLOSE))",
    "gtja_070": "(ts_std((CLOSE - ts_delay(CLOSE, 1)), 10) - ts_delay(ts_std((CLOSE - ts_delay(CLOSE, 1)), 10), 1))",
    "gtja_071": "(-ts_cov((CLOSE - ts_delay(CLOSE, 1)), ts_delay((CLOSE - ts_delay(CLOSE, 1)), 1), 20))",
    "gtja_072": "(-((HIGH - LOW) / (ts_mean(CLOSE, 20) + 0.001)))",
    "gtja_073": "(-(ts_std(VOLUME, 20) / (ts_mean(VOLUME, 20) + 0.001)))",
    "gtja_074": "((-ts_std((CLOSE - ts_delay(CLOSE, 1)), 20)) - ts_rank(VOLUME, 20))",
    "gtja_075": "(-ts_rank(ts_std((CLOSE - ts_delay(CLOSE, 1)), 20), 20))",
    "gtja_076": "(-ts_regression((CLOSE - ts_delay(CLOSE, 1)), (CLOSE - ts_delay(CLOSE, 1)), 60, 0))",
    "gtja_077": "(-ts_std(((CLOSE - ts_min(CLOSE, 20)) / ((ts_max(CLOSE, 20) - ts_min(CLOSE, 20)) + 0.001)), 10))",
    "gtja_078": "(-ts_std((CLOSE - ts_delay(ts_mean(CLOSE, 10), 1)), 20))",
    "gtja_079": "(-ts_rank(ts_sum(abs((CLOSE - ts_delay(CLOSE, 1))), 20), 20))",
    "gtja_080": "(-(ts_std(CLOSE, 20) / (ts_mean(CLOSE, 20) + 0.001)))",
    "gtja_081": "(VOLUME / (ts_mean(VOLUME, 20) + 0.001))",
    "gtja_082": "(VOLUME / (ts_mean(VOLUME, 5) + 0.001))",
    "gtja_083": "(VOLUME / (ts_mean(VOLUME, 60) + 0.001))",
    "gtja_084": "ts_rank(VOLUME, 5)",
    "gtja_085": "ts_rank(VOLUME, 20)",
    "gtja_086": "(VOLUME - ts_delay(VOLUME, 1))",
    "gtja_087": "(VOLUME - ts_delay(VOLUME, 5))",
    "gtja_088": "(ts_sum(VOLUME, 5) / (ts_sum(VOLUME, 20) + 0.001))",
    "gtja_089": "(ts_sum(VOLUME, 10) / (ts_sum(VOLUME, 60) + 0.001))",
    "gtja_090": "(ts_mean(VOLUME, 5) - ts_mean(VOLUME, 20))",
    "gtja_091": "(ts_max(VOLUME, 20) / (VOLUME + 0.001))",
    "gtja_092": "((VOLUME / (ts_mean(VOLUME, 20) + 0.001)) * (CLOSE - ts_delay(CLOSE, 1)))",
    "gtja_093": "ts_corr(VOLUME, CLOSE, 10)",
    "gtja_094": "ts_corr(VOLUME, (CLOSE - ts_delay(CLOSE, 1)), 10)",
    "gtja_095": "ts_rank((VOLUME - ts_delay(VOLUME, 5)), 10)",
    "gtja_096": "ts_decay_linear((VOLUME - ts_mean(VOLUME, 20)), 10)",
    "gtja_097": "ts_zscore(VOLUME, 20)",
    "gtja_098": "(VOLUME * abs((CLOSE - ts_delay(CLOSE, 1))))",
    "gtja_099": "(-ts_rank(VOLUME, 10))",
    "gtja_100": "ts_std(VOLUME, 20)",
    "gtja_101": "cs_rank(VOLUME)",
    "gtja_102": "(sign((CLOSE - OPEN)) * VOLUME)",
    "gtja_103": "cs_rank((VOLUME * VWAP))",
    "gtja_104": "(((CLOSE - OPEN) * VOLUME) / (OPEN + 0.001))",
    "gtja_105": "ts_sum((sign((CLOSE - OPEN)) * VOLUME), 5)",
    "gtja_106": "ts_sum((sign((CLOSE - OPEN)) * VOLUME), 20)",
    "gtja_107": "(ts_sum((sign((CLOSE - OPEN)) * VOLUME), 5) - ts_delay(ts_sum((sign((CLOSE - OPEN)) * VOLUME), 5), 5))",
    "gtja_108": "ts_corr((sign((CLOSE - OPEN)) * VOLUME), (CLOSE - ts_delay(CLOSE, 1)), 20)",
    "gtja_109": "ts_rank(((CLOSE - OPEN) * VOLUME), 10)",
    "gtja_110": "(((CLOSE - OPEN) * VOLUME) / (ts_mean((CLOSE * VOLUME), 20) + 0.001))",
    "gtja_111": "((ts_sum(VOLUME, 5) / (ts_sum(VOLUME, 20) + 0.001)) * (CLOSE - ts_delay(CLOSE, 1)))",
    "gtja_112": "ts_mean((VOLUME * (CLOSE - ts_delay(CLOSE, 1))), 5)",
    "gtja_113": "(ts_mean((VOLUME * (CLOSE - ts_delay(CLOSE, 1))), 5) / (ts_std((CLOSE - ts_delay(CLOSE, 1)), 20) + 0.001))",
    "gtja_114": "ts_rank((VOLUME * VWAP), 20)",
    "gtja_115": "(sqrt((HIGH * LOW)) / CLOSE)",
    "gtja_116": "(-((HIGH - CLOSE) / (CLOSE + 0.001)))",
    "gtja_117": "((CLOSE - LOW) / (CLOSE + 0.001))",
    "gtja_118": "((CLOSE - OPEN) / ((HIGH - LOW) + 0.001))",
    "gtja_119": "((CLOSE - ts_mean(((HIGH + LOW) / 2), 20)) / ((0.015 * ts_mean(abs((CLOSE - ts_mean(CLOSE, 20))), 20)) + 0.001))",
    "gtja_120": "((ts_mean(((CLOSE - ts_delay(CLOSE, 1)) if (CLOSE - ts_delay(CLOSE, 1)) else 0.0), 14) / (ts_mean(abs((CLOSE - ts_delay(CLOSE, 1))), 14) + 0.001)) - 0.5)",
    "gtja_121": "(-((ts_max(HIGH, 14) - CLOSE) / ((ts_max(HIGH, 14) - ts_min(LOW, 14)) + 0.001)))",
    "gtja_122": "ts_decay_linear((sign((CLOSE - OPEN)) * VOLUME), 10)",
    "gtja_123": "(((VOLUME - ts_mean(VOLUME, 20)) * (CLOSE - ts_delay(CLOSE, 1))) if (CLOSE - ts_delay(CLOSE, 1)) else (-((VOLUME - ts_mean(VOLUME, 20)) * abs((CLOSE - ts_delay(CLOSE, 1))))))",
    "gtja_124": "((-ts_rank(VOLUME, 10)) - ts_rank((CLOSE - ts_delay(CLOSE, 1)), 10))",
    "gtja_125": "(ts_rank(VOLUME, 10) * ts_rank((CLOSE - ts_delay(CLOSE, 1)), 5))",
    "gtja_126": "(ts_delay(ts_mean(VOLUME, 5), 1) - ts_delay(ts_mean(VOLUME, 20), 1))",
    "gtja_127": "((sign((CLOSE - OPEN)) * VOLUME) * ((HIGH - LOW) / (CLOSE + 0.001)))",
    "gtja_128": "cs_rank(ts_argmax(VOLUME, 20))",
    "gtja_129": "ts_std((VOLUME * (CLOSE - ts_delay(CLOSE, 1))), 20)",
    "gtja_130": "(ts_decay_linear(CLOSE, 5) / (ts_decay_linear(CLOSE, 20) + 0.001))",
    "gtja_131": "(-ts_mean((CLOSE * VOLUME), 20))",
    "gtja_132": "(-cs_rank((CLOSE * VOLUME)))",
    "gtja_133": "((-cs_rank((CLOSE * VOLUME))) * (CLOSE - ts_delay(CLOSE, 1)))",
    "gtja_134": "(CLOSE - ts_mean(CLOSE, 60))",
    "gtja_135": "(CLOSE / (ts_max(CLOSE, 252) + 0.001))",
    "gtja_136": "(CLOSE - ts_delay(CLOSE, 60))",
    "gtja_137": "(CLOSE - ts_delay(CLOSE, 120))",
    "gtja_138": "ts_rank((CLOSE / (ts_max(CLOSE, 252) + 0.001)), 20)",
    "gtja_139": "cs_rank(ts_argmax(CLOSE, 252))",
    "gtja_140": "(-(CLOSE - ts_delay(CLOSE, 252)))",
    "gtja_161": "(ts_delay(ts_mean(CLOSE, 12), 1) - ts_delay(ts_mean(CLOSE, 26), 1))",
    "gtja_162": "ts_delay(ts_mean((ts_delay(ts_mean(CLOSE, 12), 1) - ts_delay(ts_mean(CLOSE, 26), 1)), 9), 1)",
    "gtja_163": "((ts_delay(ts_mean(CLOSE, 12), 1) - ts_delay(ts_mean(CLOSE, 26), 1)) - ts_delay(ts_mean((ts_delay(ts_mean(CLOSE, 12), 1) - ts_delay(ts_mean(CLOSE, 26), 1)), 9), 1))",
    "gtja_164": "((2 * ts_std(CLOSE, 20)) / (ts_delay(ts_mean(CLOSE, 20), 1) + 0.001))",
    "gtja_165": "((CLOSE - (ts_delay(ts_mean(CLOSE, 20), 1) - (2 * ts_std(CLOSE, 20)))) / ((4 * ts_std(CLOSE, 20)) + 0.001))",
    "gtja_166": "(CLOSE - (ts_delay(ts_mean(CLOSE, 20), 1) + (2 * ts_std(CLOSE, 20))))",
    "gtja_167": "(CLOSE - (ts_delay(ts_mean(CLOSE, 20), 1) - (2 * ts_std(CLOSE, 20))))",
    "gtja_168": "((CLOSE - ts_delay(ts_mean(CLOSE, 20), 1)) / (ts_std(CLOSE, 20) + 0.001))",
    "gtja_169": "(ts_delay(ts_mean(CLOSE, 5), 1) - ts_delay(ts_mean(CLOSE, 10), 1))",
    "gtja_170": "(ts_delay(ts_mean(CLOSE, 5), 1) - ts_delay(ts_mean(CLOSE, 20), 1))",
    "gtja_171": "(ts_delay(ts_mean(CLOSE, 10), 1) - ts_delay(ts_mean(CLOSE, 30), 1))",
    "gtja_172": "(ts_delay(ts_mean(CLOSE, 5), 1) - ts_delay(ts_mean(CLOSE, 60), 1))",
    "gtja_173": "((ts_delay(ts_mean(CLOSE, 5), 1) - ts_delay(ts_mean(CLOSE, 10), 1)) + (ts_delay(ts_mean(CLOSE, 10), 1) - ts_delay(ts_mean(CLOSE, 20), 1)))",
    "gtja_174": "((CLOSE - OPEN) / (OPEN + 0.001))",
    "gtja_175": "((HIGH - OPEN) / (OPEN + 0.001))",
    "gtja_176": "(-((OPEN - LOW) / (OPEN + 0.001)))",
    "gtja_177": "(ts_mean((HIGH - LOW), 5) / CLOSE)",
    "gtja_178": "(ts_mean((HIGH - LOW), 20) / CLOSE)",
    "gtja_179": "((CLOSE - VWAP) / (VWAP + 0.001))",
    "gtja_180": "cs_rank(VWAP)",
    "gtja_181": "(VOLUME if (CLOSE - ts_delay(CLOSE, 1)) else (-VOLUME))",
    "gtja_182": "(ts_rank(CLOSE, 10) - ts_rank(CLOSE, 60))",
    "gtja_183": "(ts_rank(CLOSE, 10) - ts_rank(CLOSE, 20))",
    "gtja_184": "((ts_delay(ts_mean(CLOSE, 5), 1) - ts_delay(ts_mean(CLOSE, 20), 1)) * (VOLUME / (ts_mean(VOLUME, 20) + 0.001)))",
    "gtja_185": "ts_sum((sign((CLOSE - ts_delay(CLOSE, 1))) * VOLUME), 20)",
    "gtja_186": "ts_corr(ts_delay(ts_mean(CLOSE, 5), 1), ts_delay(ts_mean(CLOSE, 20), 1), 30)",
    "gtja_187": "(((CLOSE - ts_delay(CLOSE, 1)) if (CLOSE - ts_delay(CLOSE, 1)) else (-(CLOSE - ts_delay(CLOSE, 1)))) * (VOLUME / (ts_mean(VOLUME, 10) + 0.001)))",
    "gtja_188": "ts_rank(ts_delay(ts_mean(CLOSE, 5), 1), 20)",
    "gtja_189": "(cs_rank(CLOSE) - cs_rank((CLOSE - ts_delay(CLOSE, 1))))",
    "gtja_190": "ts_rank(ts_std(CLOSE, 10), 20)",
    "gtja_191": "ts_corr(cs_rank(CLOSE), cs_rank(VOLUME), 20)",
}
